MANGA_CATEGORIES = [
    ('art', "арт"),
    ('action', "боевик"),
    ('martial arts', "боевые искусства"),
    ('vampire', "вампиры"),
    ('harem', "гарем"),
    ('gender intrigue', "гендерная интрига"),
    ('heroic fantasy', "героическое фэнтези"),
    ('detective', "детектив"),
    ('josei', "дзёсэй"),
    ('doujinshi', "додзинси"),
    ('drama', "драма"),
    ('game', "игра"),
    ('history', "история"),
    ('cyberpank', "киберпанк"),
    ('kodomo', "кодомо"),
    ('comedy', "комедия"),
    ('maho shojo', "махо-сёдзё"),
    ('mechanics', "меха"),
    ('science fiction', "научная фантастика"),
    ('daily routine', "повседневность"),
    ('post-apocalyptic', "постапокалиптика"),
    ('adventures', "приключения"),
    ('psychology', "психология"),
    ('romantic', "романтика"),
    ('samurai action', "самурайский боевик"),
    ('supernatural', "сверхъестественное"),
    ('shojo', "сёдзё"),
    ('shojo ai', "сёдзё-ай"),
    ('shonen', "сёнэн"),
    ('shonen ai', "сёнэн-ай"),
    ('sport', "спорт"),
    ('seinen', "сэйнэн"),
    ('tragedy', "трагедия"),
    ('thriller', "триллер"),
    ('horror', "ужасы"),
    ('fantasy', "фэнтези"),
    ('school', "школа"),
    ('etti', "этти"),
    ('yuri', "юри")]
