# Generated by Django 2.2.7 on 2019-12-09 15:25

import apps.manga_api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manga_api', '0002_auto_20191209_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangavolume',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(apps.manga_api.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by user'),
        ),
    ]
