# Generated by Django 2.2.7 on 2019-12-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga_api', '0003_mangavolume_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mangaimage',
            old_name='part',
            new_name='volume',
        ),
    ]
