# Generated by Django 2.2.7 on 2019-12-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_api', '0004_auto_20191209_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangaartist',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='url'),
        ),
    ]
