# Generated by Django 2.2.7 on 2019-12-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga_api', '0005_auto_20191209_2317'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mangavolume',
            unique_together={('volume', 'manga')},
        ),
    ]
