# Generated by Django 2.2.7 on 2019-12-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga_api', '0009_auto_20191214_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='categories',
        ),
    ]
