# Generated by Django 2.2.7 on 2019-12-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_api', '0010_remove_manga_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Rating'),
        ),
    ]
