# Generated by Django 2.2.7 on 2019-12-15 08:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_api', '0011_auto_20191214_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='artists',
        ),
        migrations.AddField(
            model_name='manga',
            name='artists',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, verbose_name='Artists'), blank=True, default=['thoughts', 'django'], size=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MangaArtist',
        ),
    ]
