# Generated by Django 2.2.7 on 2019-12-17 09:20

import apps.manga_api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manga_api', '0012_auto_20191215_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='create_by_user',
            field=models.ForeignKey(null=True, on_delete=models.SET(apps.manga_api.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='Create by user'),
        ),
    ]
