# Generated by Django 2.2.7 on 2019-12-17 09:22

import apps.manga_api.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_api', '0013_manga_create_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='artists',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, verbose_name='Artists'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='manga',
            name='create_by_user',
            field=models.ForeignKey(on_delete=models.SET(apps.manga_api.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='Create by user'),
        ),
    ]
