# Generated by Django 2.2.7 on 2019-12-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_api', '0015_auto_20191217_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='english_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='English title'),
        ),
    ]
