# Generated by Django 3.0.1 on 2019-12-20 16:26

import apps.manga_api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga_api', '0016_auto_20191217_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.FileField(upload_to=apps.manga_api.models.get_archive_path, verbose_name='Archive')),
                ('manga_volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga_api.MangaVolume', verbose_name='Manga volume')),
            ],
            options={
                'verbose_name': 'Archive',
                'verbose_name_plural': 'Archives',
            },
        ),
    ]
