# Generated by Django 3.0.1 on 2019-12-25 12:53

import apps.manga_api.models
import apps.manga_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_api', '0017_mangaarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='poster',
            field=models.ImageField(blank=True, upload_to=apps.manga_api.models.get_poster_path, verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='mangaarchive',
            name='archive',
            field=models.FileField(upload_to=apps.manga_api.models.get_archive_path, validators=[apps.manga_api.validators.validate_file_size_and_ext], verbose_name='Archive'),
        ),
    ]
