# Generated by Django 3.0.1 on 2019-12-28 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga_api', '0018_auto_20191225_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangaarchive',
            name='manga_volume',
        ),
        migrations.AddField(
            model_name='mangaarchive',
            name='manga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manga_api.Manga', verbose_name='Manga volume'),
        ),
        migrations.AddField(
            model_name='mangaarchive',
            name='volume',
            field=models.IntegerField(default=1, verbose_name='volume'),
        ),
    ]
