# Generated by Django 3.0.1 on 2020-01-03 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga_api', '0019_auto_20191228_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangaarchive',
            name='manga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manga_api.Manga', verbose_name='Manga'),
        ),
    ]
