# Generated by Django 2.2.7 on 2019-11-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MangaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MangaPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manga_russian_name', models.CharField(max_length=100, verbose_name='Название на русском')),
                ('manga_original_name', models.CharField(max_length=100, verbose_name='Оригинальное название')),
                ('manga_english_name', models.CharField(max_length=100, verbose_name='Название на английском')),
                ('volumes', models.IntegerField(verbose_name='Количество томов')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('author', models.ManyToManyField(related_name='Сценарист', to='profile_api.MangaPerson')),
                ('categories', models.ManyToManyField(related_name='Категории', to='profile_api.MangaCategory')),
                ('drawer', models.ManyToManyField(related_name='Художник', to='profile_api.MangaPerson')),
                ('translation', models.ManyToManyField(related_name='Переводчик', to='profile_api.MangaPerson')),
            ],
        ),
    ]
