# Generated by Django 2.2.7 on 2019-11-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0002_auto_20191116_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manga',
        ),
        migrations.DeleteModel(
            name='MangaCategory',
        ),
        migrations.DeleteModel(
            name='MangaPerson',
        ),
        migrations.DeleteModel(
            name='MangaPoster',
        ),
    ]
