# Generated by Django 2.2.7 on 2019-12-09 14:40

import apps.custom_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=apps.custom_user.models.get_default_avatar, upload_to=apps.custom_user.models.get_avatar_path, verbose_name='Аватарка'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ник'),
        ),
    ]
