# Generated by Django 3.0.1 on 2020-01-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_int',
            field=models.IntegerField(default=4, verbose_name='Vote rating'),
            preserve_default=False,
        ),
    ]
